### PR TITLE
Fix #220: Bump lower bound of Win32 to 2.4

### LINKED ISSUE #220: process-1.6.13.2 does not build with Win32-2.3.1.1
process-1.6.13.2 does not build with Win32-2.3.1.1:
```
[4 of 5] Compiling System.Process   ( System\Process.hs, dist\build\System\Process.o )

System\Process.hs:97:44: error:
    Module ‘System.Win32.Process’ does not export ‘getCurrentProcessId’
   |
97 | import System.Win32.Process (getProcessId, getCurrentProcessId, ProcessId)
   |                                            ^^^^^^^^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by andreasabel**
Fix #220: Bump lower bound of Win32 to 2.4

Since v1.6.12.0, process does not build any more with Win32-2.2/3.
I made the necessary revisions on hackage, but the next releases should include this PR.

### CODE REVIEW

**Review by snoyberg — APPROVED** [review]
Thanks!
