### ISSUE TITLE
GHC 7.8 on Windows

### ISSUE THREAD

**Issue by kazu-yamamoto** [haskell/process#150]
Build fails with the following error:

```
Building library for process-1.6.3.0..
[1 of 5] Compiling System.Process.Common ( System\Process\Common.hs, dist\build\System\Process\Common.o )
[2 of 5] Compiling System.Process.Windows ( dist\build\System\Process\Windows.hs, dist\build\System\Process\Windows.o )
SystemProcessWindows.hsc:208:28:
    Not in scope: `<$>'
    Perhaps you meant one of these:
      `</>' (imported from System.FilePath),
      `<.>' (imported from System.FilePath)
cabal.exe: Failed to build process-1.6.3.0 (which is required by network-3.1.1.0).
```

**Comment by snoyberg** [comment]
Looks like it was introduced in ae57e8c22b4e7f8356b1f21744add5b2f4d462b1. Following the "when in Rome" principle, I've added a Hackage revision to disallow this combination for process version and GHC version.

**Comment by RyanGlScott** [comment]
The same issue affects `process-1.6.2.0`, as shown [here](https://ci.appveyor.com/project/RyanGlScott/text-show-instances/builds/27153990/job/837dvsqq5qtw6xwd).

**Comment by RyanGlScott** [comment]
I decided to be a bit more thorough and test other versions of `process` on my Windows machine with GHC 7.8.4 installed. Here are all the versions that fail to build on 7.8.4 due to the same `Not in scope: '<$>'` issue:

* 1.5.0.0
* 1.6.0.0
* 1.6.1.0
* 1.6.2.0

This seems to match up with the git history for the [offending commit](https://github.com/haskell/process/commit/ae57e8c22b4e7f8356b1f21744add5b2f4d462b1), which GitHub claims debuted in version 1.5.0.0.

**Comment by snoyberg** [comment]
Revisions released for those, thanks for listing them.

**Comment by kazu-yamamoto** [comment]
I confirmed that this is fixed. Thanks!

**Comment by hvr** [comment]
Just for the record: I've re-revised the affected releases' metadata to address this more adequately as the revisions that were performed imprudently were cutting off legitimate solutions for no reason; I suggest cc'ing hackage trustees for assistance for maybe not so obvious cases such as this one.
