### ISSUE TITLE
process-1.6.3.0 doesn't build with GHC 7.8.4 on Windows

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/process#131]
```
[2 of 5] Compiling System.Process.Windows ( dist\build\System\Process\Windows.hs, dist\build\System\Process\Windows.o )
SystemProcessWindows.hsc:208:28:
    Not in scope: `<$>'
    Perhaps you meant one of these:
      `</>' (imported from System.FilePath),
      `<.>' (imported from System.FilePath)
cabal.exe: Failed to build process-1.6.3.0 (which is required by test:test from HTTP-4000.3.11).
```

The culprit seems to be ae57e8c22b4e7f8356b1f21744add5b2f4d462b1.

Fixing this should be easy: just replace `<$>` with `fmap`. But we should also add a 7.8.4 AppVeyor configuration.

**Comment by snoyberg** [comment]
Is there a specific reason to need support for older GHCs? I'm leaning towards dropping older compiler support to make contributions easier.

**Comment by 23Skidoo** [comment]
I saw that 7.8 configuration was enabled on Travis, so I assumed that it was supported. If you decide to drop support for older GHCs, please also bump the lower bound on `base` to correspond to the earliest supported GHC version (preferably for existing Hackage releases as well). The point about improving Windows CI still stands.

**Comment by hsenag** [comment]
I don't care about the latest version supporting old GHCs, as long as the bounds of anything that's released expresses that.

**Comment by snoyberg** [comment]
I've dropped support for GHC < 7.10.3 in PR #134, which also increases the AppVeyor and Travis matrices. I'm not certain what to do about Hackage revisions, if any, since adding a lower bound will break currently working build plans on non-Windows systems. I know I've been bitten by revisions which break existing build plans in the past, so my inclination is to do nothing.

**Comment by 23Skidoo** [comment]
Great, thanks. Re: bumping the lower bound, in principle the following could work:

```
if os(windows)
    build-depends: base >= 4.8
```

except that revisions currently don't allow adding new conditionals. Perhaps that restriction should be relaxed slightly.

**Comment by snoyberg** [comment]
I definitely don't want to open the door any wider for revisions based on this case (or any other). Future releases of process will have the stricter lower bound in place. I'm going to close this for now, and if somehow it causes problems for people in the future, we can investigate further.
