### ISSUE TITLE
 process-1.6.13.2 does not build with Win32-2.3.1.1

### ISSUE THREAD

**Issue by andreasabel** [haskell/process#220]
process-1.6.13.2 does not build with Win32-2.3.1.1:
```
[4 of 5] Compiling System.Process   ( System\Process.hs, dist\build\System\Process.o )

System\Process.hs:97:44: error:
    Module ‘System.Win32.Process’ does not export ‘getCurrentProcessId’
   |
97 | import System.Win32.Process (getProcessId, getCurrentProcessId, ProcessId)
   |                                            ^^^^^^^^^^^^^^^^^^^
```

**Comment by andreasabel** [comment]
This change was introduced in commit dcaa85c5b0802f94e1792384ba55f552ec1bce62, released in 1.6.12.0.  Thus, all releases starting 1.6.12.0 need their lower bound to be bumped to Win32 >= 2.4.
I will make the respective revisions.
